language: php

php:
  - 7.0

env:
  - SELENIUM_URL='http://localhost:8000/' TZ='Europe/Rome'

sudo: false

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar -O selenium.jar
  - java -jar selenium.jar -browserSessionReuse &> selenium.log &
  - sleep 30

install:
  - composer install --dev

before_script:
  - phpenv config-add ci/config/php.ini
  - echo 'CREATE DATABASE universibo' | psql -U postgres
  - echo 'CREATE DATABASE universibo_forum3' | psql -U postgres
  - echo "CREATE USER universibo WITH PASSWORD 'universibo'" | psql -U postgres
  - echo "GRANT ALL PRIVILEGES ON DATABASE universibo TO universibo" | psql -U postgres
  - echo "GRANT ALL PRIVILEGES ON DATABASE universibo_forum3 TO universibo" | psql -U postgres
  - cat app/sql/pgsql/devdb.sql | psql -U postgres universibo
  - cat vendor/universibo/forum-bundle/Universibo/Bundle/ForumBundle/Tests/Resources/sql/{structure,data}-postgres.sql | sed 's/OWNER TO.*/OWNER TO universibo;/' | psql -U postgres universibo_forum3
  - app/console server:run &> server.log &

script:
  - bin/phpunit -c app --coverage-clover=coverage.clover
  - bin/behat @UniversiboDashboardBundle -v
  - bin/behat @UniversiboWebsiteBundle -v

notifications:
  email: dev_universibo@mama.ing.unibo.it

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - cat *.log
