# vim: set tabstop=2 shiftwidth=2 expandtab:
version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/project
    links:
      - db
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
  db:
    image: "postgres:latest"
    volumes:
      - "./data/postgresql:/var/lib/postgresql/data"
      - "./app/sql/pgsql:/sql"
