<?php

include ('UniversiboCommand'.PHP_EXTENSION);

/**
 * ShowContacts is an extension of UniversiboCommand class.
 *
 * It shows Contacts page
 *
 * @package universibo
 * @version 2.0.0
 * @author Fabrizio Pinto
 * @author Ilias Bartolini <brain79@virgilio.it>
 * @license GPL, {@link http://www.opensource.org/licenses/gpl-license.php}
 */
 
class ShowContacts extends UniversiboCommand {
	function execute()
	{

		$template =& $this->frontController->getTemplateEngine();
		
		$template->assign('contacts_altTitle', 'Chi Siamo');
		$template->assign('contacts_intro', 'Lo sviluppo di questo sito è principalmente opera di un team di studenti che ha lavorato in stretto contatto con l\'amministratore di sistema: un tecnico informatico che si è lasciato appassionare dal progetto. Qui di seguito ci presentiamo indicandovi una divisione in ruoli per aiutarvi nel decidere chi contattare, qualora aveste quesiti o consigli da rivolgerci.');
		//inizio array di array contenenti i vari chi siamo 

		$template->assign('contacts_personal', array(
			'contacts_brain'=>array('nick'=>'brain', 'intro'=>'Brain è un caparbio studente di Ingegneria Informatica. Nel progetto si occupa del lavoro più importante: la progettazione del software e di buona parte della grafica.', 'ruolo'=>'amministratore - progettista software', 'email'=>'brain79@virgilio.it', 'recapito'=>'3381407176', 'obiettivi'=>'Obiettivo iniziale del mio progetto era semplicemente mettere in pratica le prime conoscenze acquisite riguardo HTML, PHP e la realizzazione di applicazioni Web.
Aver portato avanti il mio primo progetto mi ha sicuramente fatto piacevolmente imparare molte cose e insieme al lato didattico sono arrivate enormi gratificazioni personali da altri amici, studenti e anche docenti, per aver creato nel mio piccolo qualcosa di grosso aiuto per gli altri... e queste gratificazioni mi hanno spinto ad impegnarmi ancora di più ad accrescere le mie conoscenze... un circolo virtuoso...
Appena ho conosciuto altri due matti con un progetto simile al mio... beh, quale migliore occasione per aprire un manicomio... e subito altri matti hanno risposto all\'appello 
Ora c\'è il piacere di poter imparare a lavorare in gruppo, dividere e condividere il lavoro pur mantenendo ognuno la libertà di fare quel che gli pare!!!
Nuove conoscenze... Progettazione e strutture grafiche web, Basi di Dati, Amministrazione e configurazione del web Server, Gestione di del Progetto in gruppo.... e ad approfondire quelle di prima (...è proprio vero che non si finisce mai di imparare!!!)'),
			'contacts_by_post'=>array('nick'=>'by_post', 'intro'=>'Studentessa di Ingegneria Gestionale. Nel progetto si occupa insieme a Matteo della grafica del sito e della stesura di pagine HTML', 'ruolo'=>'amministratore - responsabile della grafica', 'email'=>'by_post@hotmail.com', 'recapito'=>'-', 'obiettivi'=>'Ho iniziato a collaborare con Andrea e Matteo alla moderazione della mailing list per i gestionali e quando è iniziato il progetto di UniversiBO è stato praticamente impossibile non farmi coinvolgere. Ho sempre avuto il pallino del computer ma non ho mai avuto modo di approfondire... ora non solo ho l\'opportunità di imparare tante cose ma quel che faccio mi piace e mi da soddisfazione. Ogni giorno ho modo di confrontarmi, di imparare e sperimentare cosa vuol dire lavorare in gruppo... se a tutto questo aggiungiamo che questo gruppo di matti è straordinario... il gioco è fatto! '),
			'contacts_eagleone'=>array('nick'=>'eagleone', 'intro'=>'Studente di Ingegneria Gestionale da sempre fissato con l\'informatica. Nel progetto si occupa in particolar modo della gestione e della documentazione.', 'ruolo'=>'amministratore - gestione progetto e documentazione', 'email'=>'eagleone@libero.it', 'recapito'=>'3394323246', 'obiettivi'=>'Grazie all\'iniziativa di matteo di fondare la mailing list dei gestionali, ho avuto l\'opportunità di gestire una comunità di studenti. Già tale attività comporta una notevole spesa di tempo e sicuramente il carico del progetto sarà molto più pesante, ma so che quando il sito sarà realizzato la soddisfazione ripagherà tutte le fatiche. Il motivo forte che mi spinge ogni giorno a lavorare per il progetto è che ciò che faccio proprio mi piace: mi diverto a programmare, ma soprattutto mi piace dedicare tempo alla gestione del progetto e questo proprio perché diventare direttore di progetti di innovazione(in particolar modo di software) è ciò che aspiro per il mio futuro. Quale miglior occasione per fare esperienza di questa? '),
			'contacts_fgiardini'=>array('nick'=>'fgiardini', 'intro'=>'Studente di Ingegneria dei Processi Gestionali, collabora nelle sezioni di Gestione e Documentazione. E\' responsabile in particolare della sezione Benchmarking e delle Attività Offline a questa correlate.', 'ruolo'=>'amministratore - gestione e documentazione', 'email'=>'fgiardini@freemail.it', 'recapito'=>'3283030235', 'obiettivi'=>'È senz\'altro una possibilità più unica che rara per fare esperienza diretta in un team di progetto! [...]

Bla bla bla... Avevo scritto un profilo molto serio e barboso, e rileggendolo sembrava scritto da un ingegnere e ho preso paura... quindi tabula rasa e se volete sapere qualcosa in più su di me non avete che da chiamarmi. No, gli insulti non sono graditi...
P.S.
Non ho ancora ben capito che animale sia un Ingegnere dei Processi Gestionali, ma arriverò in fondo a questa storia! Ciau! '),
		
			'contacts_gianluca'=>array('nick'=>'gianluca', 'intro'=>'Responsabile informatico del Cieg, con la passione per il software Open Source.', 'ruolo'=>'amministratore di sistema e addetto alla sicurezza', 'email'=>'gianluca@joker.ing.unibo.it', 'recapito'=>'0512093946', 'obiettivi'=>'I miei obiettivi sono "istituzionali" nel senso che fanno parte del mio ruolo lavorativo presso il Cieg e principalmente comprendono l\'amministrazione dell\'infrastruttura informatica di una parte della sede di via Saragozza n.8. Questo progetto si discosta leggermente rispetto alle situazioni standard incontrate fino ad ora e non so se inserirlo nella lista dei compiti "istituzionali", ma comunque ha ricevuto il mio appoggio fin dal principio. Lavorare con gli altri membri dello staff permette di creare un circolo virtuoso di scambio di idee e quindi ognuno di noi può imparare qualcosa dagli altri.'),
		    'contacts_matteo'=>array('nick'=>'Matteo', 'intro'=>'Studente di Ingegneria Gestionale super esperto in informatica. Nel progetto si occupa dell\'amministrazione di sistema e del design grafico.', 'ruolo'=>'amministratore - sistemista e designer', 'email'=>'vignolimatteo@virgilio.it', 'recapito'=>'Ora sono a San Diego! Se volete contatatrmi mandatemi una mail', 'obiettivi'=>'Le motivazioni che mi spingono a lavorare su questo progetto sono strutturate, nel senso che si sono ampliate e modificate col tempo. Alla radice c\'è sicuramente il desiderio di creare qualcosa di utile, poi mi piace l\'idea di applicare quello che studio a qualcosa di concreto. L\'esperienza di gestione della mailing list ha contribuito ad accrescere la voglia di implementare un servizio creato dagli studenti e per gli studenti. Queste forse sono le motivazioni a più basso livello, quelle che c\'erano fin dall\'inizio e che si sono mantenute; a rinforzo di queste, con l\'avanzare del progetto il gruppo che si è formato e le gratificazioni ricevute da professori e compagni mi hanno spinto e mi spingono ad andare avanti ben consapevole dell\'importanza del servizio che andremo a offrire.'),
			'contacts_spiff1281'=>array('nick'=>'spiff1281', 'intro'=>'', 'ruolo'=>'amministratore - attività offline', 'email'=>'spiff1281@email.it', 'recapito'=>'339 2888793', 'obiettivi'=>'Ho iniziato a collaborare a UniversiBO perché mi dava la possibilità di imparare cose che sui libri o in un aula universitaria non è possibile imparare. Con UniversiBO ho conosciuto molti amici, che mi hanno aiutato ad imparare e crescere le mie conoscenze tecniche e non. '),
			'contacts_ax80'=>array('nick'=>'ax80', 'intro'=>'Studente di Ingegneria Gestionale, proveniente da Macerata, tifoso del Milan', 'ruolo'=>'moderatore', 'email'=>'serraalberto@libero.it', 'recapito'=>'3392517183', 'obiettivi'=>'Aiutare il gruppo a realizzare un sito ben fatto e specialmente utile e di facile comprensione. E poi la gratificazione di un lavoro ben fatto è il massimo che si possa chiedere..'),
			'contacts_budwhite'=>array('nick'=>'BudWhite', 'intro'=>'Bukowski non si sarebbe mai arreso alla settima ripresa. Tra il dire e il fare, chi visse sperando. Piove.', 'ruolo'=>'moderatore - collaboratore', 'email'=>'schlomele@libero.it', 'recapito'=>'3496692919', 'obiettivi'=>'Cerco di dare una mano, quando posso. Non è facile gestire la vita universitaria, gli esami, le donne e il vino, ma sono un gestionale, del resto. E\' uno sporco lavoro, ma qualcuno deve pur farlo, non credete ?'),
			'contacts_chiaretta'=>array('nick'=>'chiaretta', 'intro'=>'studentessa di ingegneria delle telecomunicazioni', 'ruolo'=>'collaboratrice progettazione grafica', 'email'=>'annachiara@despammed.com', 'recapito'=>'3478005673', 'obiettivi'=>'Mi sono unita al progetto con la speranza di incrementare le mie (ridotte) capacità informatiche e contemporaneamente di poter collaborare alla progressiva realizzazione di un\'idea senz\'altro valida, quale UniversiBo mi era sembrata fin dall\'inizio. '),
			'contacts_dexterh46'=>array('nick'=>'DexterH46', 'intro'=>'Studente di Ingegneria Gestionale con tante piccole passioni.All\'interno di UniversiBo sono responsabile per alcuni esami e moderatore per altri. Mi occuperò inoltre della sezione Erasmus(col sogno di riuscire ad andarci anch\'io un giorno ;-D).', 'ruolo'=>'moderatore', 'email'=>'idjwilly@yahoo.com', 'recapito'=>'339 4489656', 'obiettivi'=>'Sono tanti e sicuramente ne dimenticherò qualcuno. Tra di essi c\'è sicuramente quello di capire ed usare (un passo per volta magari)i diversi linguaggi utilizzati nelle pagine del sito; la volontà di partecipare ad un progetto impossibile da realizzare alle superiori e che mi ha subito affascinato e trovato d\'accordo; la voglia come sempre di contribuire a creare e fornire un aiuto per tutti i compagni di Università col pensiero che "insieme le difficoltà si superano meglio" e quindi con la speranza che tutti contribuiscano nel darsi una mano(anche se purtroppo ci sarà anche chi "sfrutterà" solo il servizio vedendo nell\'amico solo un "avversario"... mah...). '),
			'contacts_jolly_82'=>array('nick'=>'Jolly_82', 'intro'=>'Studio ingegneria gestionale al 2 anno, sono studente fuori sede, proveniente dalla Marche (Fabriano). Tra un esame e l\'altro i miei hobbyes sono l\'informatica ed il netgaming mentre gli sport che seguo di più sono il Basket, lo sci e la F1. Amo fare passeggiate in mountain bike quando sono giu a casa e quassù a bologna mi orgnanizzo per le "partitelle con gli amici". In un certo senso apprezzo tutti i generi musicali senza distinzione, prediligo cmq pop e commerciale, ascolto molto la radio (105 4ever) e colleziono le musiche degli spot publicitari...', 'ruolo'=>'moderatore - collaboratore nella sezione grafica', 'email'=>'jolly_82@libero.it', 'recapito'=>'3493940611', 'obiettivi'=>'cercare di coltivare questa community perchè, come si sa, l\'unione fa la forza.... '),
			'contacts_lasthope'=>array('nick'=>'LastHope', 'intro'=>'Mi chiamo Daniele Tiles, studio Ingegneria Informatica e sono di Bologna...basta così O volete anche il numero di scarpe?', 'ruolo'=>'Al momento sono solo un moderatore e referente dei corsi di Fisica (L-A, L-B), Reti Logiche e Elettrotecnica per il corso d\'Ingegneria Informatica...', 'email'=>'daniele.tiles@studio.unibo.it ', 'recapito'=>'3284139075', 'obiettivi'=>'diventare un ingegnere, capire tutto il possibile su computer e affini...cosa volete di più? UniversiBO m\'interessa tantissimo...quando avrò le capacità adatte, entrerò anch\'io nel ramo della progettazione. Il mio obbiettivo in UniversiBO è aiutare al massimo gli studenti che arrivano...non è facile abituarsi a questo nuovo ambiente, ed UniversiBO secondo me è lo strumento ideale! '),
			'contacts_luc'=>array('nick'=>'LUC', 'intro'=>'studente di Ingegneria Gestionale ', 'ruolo'=>'collaboratore attività offline', 'email'=>'fad4716@hotmail.com', 'recapito'=>'3289760725', 'obiettivi'=>''),
			'contacts_malagucci'=>array('nick'=>'MalaGucci', 'intro'=>'MalaGucci è uno studente di Ingegneria Gestionale', 'ruolo'=>'moderatore', 'email'=>'matteo.malaguti@libero.it', 'recapito'=>'059-548308', 'obiettivi'=>'Obiettivo principale della mia partecipazione al progetto è quello di contribuire ad un servizio innovativo e di sicura utilità per tutti gli studenti .'),
			'contacts_meco'=>array('nick'=>'Meco', 'intro'=>'studente di ing gestionale patito di informatica e tutto ciò che ruota intorno ad internet', 'ruolo'=>'collaboratore nelle sezioni Test, Progettazione, Benchmarking - moderatore', 'email'=>'meco@vodafone.it', 'recapito'=>'3478005673', 'obiettivi'=>'Aumentare la mia conoscenza dei vari software nella progettazione di carattere web, conoscere le basi di un server, dalla sua realizzazione al suo mantenimento! Ma soprattutto divertirmi con un gruppo di amici!!!'),
			'contacts_mikal'=>array('nick'=>'mikal', 'intro'=>'23 anni, iscritta al IV anno di Ingegneria Gestionale, spero di uscire presto dall\'Università, ma nel frattempo vale la pena di dedicarsi un po\' al progetto UniversiBo ', 'ruolo'=>'moderatore - attività offline', 'email'=>'micolsanti@yahoo.it', 'recapito'=>'338 2305493', 'obiettivi'=>'Mi occupo quasi esclusivamente dell\'attività OffLine, contatto con i docenti in aula e in dipartimento. Mi sono trovata bene con le persone che lavorano al progetto, ho stima dell\'impegno che ci stanno mettendo e condivido le loro speranze su quello che ne verrà fuori!'),
			'contacts_nasuti_c'=>array('nick'=>'nasuti_c', 'intro'=>'sono uno studente di ingegneria delle telecomunicazioni con l\'hobby per l\'informatica (e sopratutto per gli anime)', 'ruolo'=>'faccio da referente e moderatore per alcuni esami del mio cdl e provo a realizzare qualcosa per la grafica e la stesura contenuti', 'email'=>'nasuti_c@email.it', 'recapito'=>'3331553398', 'obiettivi'=>'ciò che mi ha spinto a collaborare è stato prima di tutto la curiosità per qualcosa di nuovo, poi l\'interesse di fare quasi da tramite tra professori e studenti, con la voglia di partecipare a qualcosa di utile '),
			'contacts_orsacchio'=>array('nick'=>'orsacchio', 'intro'=>'Ma che ci va scritto????? :-) ', 'ruolo'=>'collaboratore', 'email'=>'enrico.scalavino@libero.it ', 'recapito'=>'3475214764', 'obiettivi'=>'a dire il vero non so bene neanch\'io perchè abbia deciso di collaborare a universibo, forse perchè sarà un buono stimolo per applicare ciò che studio a un progetto concreto. Visto poi l\'entusiasmo che ci mettono tutti gli altri ragazzi....beh....mi sono lasciato coinvolgere e sono convinto che questo coinvolgimento aumenterà col tempo. '),
			'contacts_pwatch'=>array('nick'=>'Pwatch', 'intro'=>'Non trovo nulla di interessante da dire a mio proposito', 'ruolo'=>'moderatore ', 'email'=>'pasquale.babini@studio.unibo.it', 'recapito'=>'328 2213798', 'obiettivi'=>'Non riesco a trovare nulla che non sia terribilmente demagogico x riempire questo campo.... '),
			'contacts_rocco83'=>array('nick'=>'Rocco83', 'intro'=>'ing. mi piace per le persone, non certo per quello che si studia. chi pensa che analisi sia utile per creare un array alzi la mano. a parte questo, sono un fanatico dei computer, scout, e pazzo! (nonchè figlio di ferroviere, e quindi non pago lu treno!)', 'ruolo'=>'sysadmin, sviluppatore sw, attività offline', 'email'=>'rocco@rimini.no-ip.com', 'recapito'=>'3402246549', 'obiettivi'=>'arrivare ad un numero di macchine amministrate talmente alto che scorderò gli ip di tutte, far capire agli utenti che la password "pippo" non è la più sicura, installare macchine da 200$ con linux e far capire a chi compra super-server-strafichi-con-windows-xp a 20000$ che le mie macchine vanno meglio e sono più sicure, essere lo zefram cochrane dei computer... '),
			'contacts_tnt'=>array('nick'=>'TnT', 'intro'=>'', 'ruolo'=>'diffusione del LaTeX quale strumento di condivisione tra gli studenti di appunti e materiale didattico in forma elettronica... più tutto il resto (ie. integrazione tra grafica e software: sviluppo del sistema dei template)', 'email'=>'tntimo@despammed.com', 'recapito'=>'', 'obiettivi'=>'Molti hanno già detto molto e forse anche troppo; cosa potrei mai aggiungere io di rilevante? Come già osservai con qualcuno, avrei dovuto elaborare questo scritto ai miei esordi nel progetto - evento che ormai si perde nel tempo e nella memoria - e non ora che ormai l\'entusiasmo iniziale va scemando. Concludo quindi questa mia divagazione già fin troppo lunga, ricordando che le persone che pensano a farsi notare, in realtà non sono quelle che contano veramente: quindi basta chiacchiere! perchè appoggio incondizionatamente la filosofia di un mio conterraneo: fatti e non pugn..'),
			'contacts_toni'=>array('nick'=>'toni', 'intro'=>'partito dalla solare città di Pescara, sto provando ad immedesimarmi nel ruolo di studente di Ingegneria Meccanica nella bella Bologna. Appena posso coltivo le mie passioni: calcio,computer e tutto ciò che è tecnologia', 'ruolo'=>'collaboratore nella sezione grafica-moderatore', 'email'=>'antonio_carminelli@hotmail.com ', 'recapito'=>'3497630035', 'obiettivi'=>'appena saputo di Universibo mi è subito piaciuto lo spirito del progetto: studenti che con passione cercano di mettere la tecnologia al servizio di altri studenti per far sì che si aiutino l\'uno con l\'altro! come non farne parte...e magari imparerò anche qualcosa!'),
			'contacts_vale83'=>array('nick'=>'vale83', 'intro'=>'studentessa di ingegneria delle telecomunicazioni', 'ruolo'=>'collaboro alle attività off-line,scrittura contenuti e moderazione', 'email'=>'cristofori@studio.unibo.it', 'recapito'=>'3295432013', 'obiettivi'=>'Mi sono unita per collaborare alla realizzazione di un servizio valido e utile come Universibo e per cercare di ampliare le mie scarse conoscenze informatiche'),
			'contacts_yukon'=>array('nick'=>'yukon', 'intro'=>'studente, cercatore d\'oro...', 'ruolo'=>'moderatore', 'email'=>'yukon@sicosbt.it', 'recapito'=>'051392346', 'obiettivi'=>'costruzione di un portale web, applicazione di tecnologie orientate al web, comunione dello scibile fra gli studenti... ')
			
			));  
		//fine array
		
		return 'default';						
	}
}

?>